<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <Description>SuperSocket Command test project for validating the command handling and processing capabilities of the framework.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SuperSocket.Command/SuperSocket.Command.csproj" />
    <ProjectReference Include="../../src/SuperSocket.Command.SourceGeneration/SuperSocket.Command.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
