using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Xunit;

namespace SuperSocket.Command.SourceGeneration.Tests;

public class CommandDiscoveryTests
{
    [Fact]
    public void Generator_EmitsDiscoveredCommandsForMatchingRegistryPackage()
    {
        var result = GeneratorTestHarness.Run("""
            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public sealed class FakePkg
            {
            }

            [Command("ADD")]
            public class AddCmd : IAsyncCommand<IAppSession, FakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, FakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            [Command("ONE", "1")]
            public class OneCmd : ICommand<IAppSession, FakePkg>
            {
                public void Execute(IAppSession session, FakePkg package)
                {
                }
            }

            [CommandRegistry]
            public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
            {
            }
            """);

        string generatedSource = result.GeneratedTrees
            .Single(static tree => tree.FilePath.EndsWith("Demo.Reg.Registry.g.cs", StringComparison.Ordinal))
            .GetText(TestContext.Current.CancellationToken)
            .ToString();

        Assert.Contains("// <auto-generated/>", generatedSource, StringComparison.Ordinal);
        Assert.Contains("public partial class Reg", generatedSource, StringComparison.Ordinal);
        Assert.Contains("GetRegistrations()", generatedSource, StringComparison.Ordinal);
        Assert.Contains("yield return new global::SuperSocket.Command.CommandRegistration<", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::SuperSocket.Command.TypedCommandSet<", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<global::Demo.AddCmd>(sp)", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::System.Array.Empty<global::SuperSocket.Command.ICommandFilter>()", generatedSource, StringComparison.Ordinal);
        Assert.Contains("Demo.AddCmd", generatedSource, StringComparison.Ordinal);
        Assert.Contains("\"ADD\"", generatedSource, StringComparison.Ordinal);
        Assert.Contains("Demo.OneCmd", generatedSource, StringComparison.Ordinal);
        Assert.Contains("\"1\"", generatedSource, StringComparison.Ordinal);
    }

    [Fact]
    public void GeneratedCode_Compiles()
    {
        Diagnostic[] diagnostics = GeneratorTestHarness.RunAndGetCompilationDiagnostics("""
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public sealed class FakePkg
            {
            }

            [Command("ADD")]
            public class AddCmd : IAsyncCommand<IAppSession, FakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, FakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            [CommandRegistry]
            public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
            {
            }
            """);

        Diagnostic[] errors = diagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.Empty(errors);
    }

    [Fact]
    public void GeneratedCode_CompilesForNestedRegistryInPublicClass()
    {
        Diagnostic[] diagnostics = GeneratorTestHarness.RunAndGetCompilationDiagnostics("""
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public sealed class FakePkg
            {
            }

            [Command("ADD")]
            public class AddCmd : IAsyncCommand<IAppSession, FakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, FakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            public partial class Outer
            {
                [CommandRegistry]
                public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
                {
                }
            }
            """);

        Diagnostic[] errors = diagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.Empty(errors);
    }

    [Fact]
    public void GeneratedCode_CompilesForNestedRegistryInGenericPublicClass()
    {
        Diagnostic[] diagnostics = GeneratorTestHarness.RunAndGetCompilationDiagnostics("""
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public sealed class FakePkg
            {
            }

            [Command("ADD")]
            public class AddCmd : IAsyncCommand<IAppSession, FakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, FakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            public partial class Outer<T>
                where T : class
            {
                [CommandRegistry]
                public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
                {
                }
            }
            """);

        Diagnostic[] errors = diagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.Empty(errors);
    }


    [Fact]
    public void Generator_WrapsCommandsWhosePackageInterfaceIsImplementedByRegistryPackage()
    {
        var result = GeneratorTestHarness.Run("""
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public interface IFakePkg
            {
            }

            public sealed class FakePkg : IFakePkg
            {
            }

            public sealed class OtherPkg
            {
            }

            [Command("ASYNC")]
            public class AsyncInterfaceCmd : IAsyncCommand<IAppSession, IFakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, IFakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            [Command("SYNC")]
            public class SyncInterfaceCmd : ICommand<IAppSession, IFakePkg>
            {
                public void Execute(IAppSession session, IFakePkg package)
                {
                }
            }

            [Command("EXACT")]
            public class ExactCmd : ICommand<IAppSession, FakePkg>
            {
                public void Execute(IAppSession session, FakePkg package)
                {
                }
            }

            [Command("MISMATCH")]
            public class MismatchCmd : ICommand<IAppSession, OtherPkg>
            {
                public void Execute(IAppSession session, OtherPkg package)
                {
                }
            }

            [CommandRegistry]
            public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
            {
            }
            """);

        string generatedSource = result.GeneratedTrees
            .Single(static tree => tree.FilePath.EndsWith("Demo.Reg.Registry.g.cs", StringComparison.Ordinal))
            .GetText(TestContext.Current.CancellationToken)
            .ToString();

        Assert.Contains("global::SuperSocket.Command.AsyncCommandWrap<global::SuperSocket.Server.Abstractions.Session.IAppSession, global::Demo.FakePkg, global::Demo.IFakePkg, global::Demo.AsyncInterfaceCmd>", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::SuperSocket.Command.CommandWrap<global::SuperSocket.Server.Abstractions.Session.IAppSession, global::Demo.FakePkg, global::Demo.IFakePkg, global::Demo.SyncInterfaceCmd>", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<global::Demo.AsyncInterfaceCmd>(sp)", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<global::Demo.SyncInterfaceCmd>(sp)", generatedSource, StringComparison.Ordinal);
        Assert.DoesNotContain("new global::SuperSocket.Command.AsyncCommandWrap<global::SuperSocket.Server.Abstractions.Session.IAppSession, global::Demo.FakePkg, global::Demo.IFakePkg, global::Demo.AsyncInterfaceCmd>(sp)", generatedSource, StringComparison.Ordinal);
        Assert.DoesNotContain("new global::SuperSocket.Command.CommandWrap<global::SuperSocket.Server.Abstractions.Session.IAppSession, global::Demo.FakePkg, global::Demo.IFakePkg, global::Demo.SyncInterfaceCmd>(sp)", generatedSource, StringComparison.Ordinal);
        Assert.Contains("global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<global::Demo.ExactCmd>(sp),", generatedSource, StringComparison.Ordinal);
        Assert.DoesNotContain("CommandWrap<global::SuperSocket.Server.Abstractions.Session.IAppSession, global::Demo.FakePkg, global::Demo.FakePkg, global::Demo.ExactCmd>", generatedSource, StringComparison.Ordinal);
        Assert.DoesNotContain("global::Demo.MismatchCmd", generatedSource, StringComparison.Ordinal);
    }

    [Fact]
    public void GeneratedCode_CompilesForCommandsWhosePackageInterfaceIsImplementedByRegistryPackage()
    {
        Diagnostic[] diagnostics = GeneratorTestHarness.RunAndGetCompilationDiagnostics("""
            using System.Threading;
            using System.Threading.Tasks;
            using SuperSocket.Command;
            using SuperSocket.Server.Abstractions.Session;

            namespace Demo;

            public interface IFakePkg
            {
            }

            public sealed class FakePkg : IFakePkg
            {
            }

            [Command("ASYNC")]
            public class AsyncInterfaceCmd : IAsyncCommand<IAppSession, IFakePkg>
            {
                public ValueTask ExecuteAsync(IAppSession session, IFakePkg package, CancellationToken cancellationToken)
                    => default;
            }

            [Command("SYNC")]
            public class SyncInterfaceCmd : ICommand<IAppSession, IFakePkg>
            {
                public void Execute(IAppSession session, IFakePkg package)
                {
                }
            }

            [CommandRegistry]
            public partial class Reg : IGeneratedCommandRegistry<string, FakePkg>
            {
            }
            """);

        Diagnostic[] errors = diagnostics
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.Empty(errors);
    }
}
