using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SuperSocket.Command.SourceGeneration.Diagnostics;
using SuperSocket.Command.SourceGeneration.Model;

namespace SuperSocket.Command.SourceGeneration.Emit;

internal static class RegistryEmitter
{
    public static string Emit(RegistryModel registry, ImmutableArray<CommandModel> commands, SourceProductionContext context)
    {
        var builder = new SourceBuilder();

        builder.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine();

        if (!string.IsNullOrWhiteSpace(registry.Namespace))
        {
            builder.AppendLine($"namespace {registry.Namespace};")
                .AppendLine();
        }

        IReadOnlyList<IDisposable> containingTypeScopes = EmitContainingTypesStart(builder, registry);
        EmitRegistryClass(builder, registry, commands, context);
        EmitContainingTypesEnd(builder, containingTypeScopes);

        return builder.ToString();
    }

    private static IReadOnlyList<IDisposable> EmitContainingTypesStart(SourceBuilder builder, RegistryModel registry)
    {
        var scopes = new List<IDisposable>();

        foreach (ContainingTypeModel containingType in registry.ContainingTypes)
        {
            builder.AppendLine(GetContainingTypeDeclaration(containingType))
                .AppendLine("{");

            scopes.Add(builder.Indent());
        }

        return scopes;
    }

    private static void EmitContainingTypesEnd(SourceBuilder builder, IReadOnlyList<IDisposable> containingTypeScopes)
    {
        for (int i = containingTypeScopes.Count - 1; i >= 0; i--)
        {
            containingTypeScopes[i].Dispose();
            builder.AppendLine("}");
        }
    }

    private static string GetContainingTypeDeclaration(ContainingTypeModel containingType)
    {
        string declaration = string.Join(
            " ",
            new[]
            {
                containingType.Accessibility,
                containingType.Modifiers,
                "partial",
                containingType.TypeKeyword,
                containingType.Name + containingType.TypeParameterList,
            }.Where(static value => !string.IsNullOrWhiteSpace(value)));

        if (containingType.ConstraintClauses.Count == 0)
        {
            return declaration;
        }

        return declaration + " " + string.Join(" ", containingType.ConstraintClauses);
    }

    private static void EmitRegistryClass(SourceBuilder builder, RegistryModel registry, ImmutableArray<CommandModel> commands, SourceProductionContext context)
    {
        builder.AppendLine($"{registry.Accessibility} partial class {registry.ClassName}")
            .AppendLine("{");

        using (builder.Indent())
        {
            if (registry.HasGetRegistrationsMethod)
            {
                ReportExistingGetRegistrations(context, registry);
                builder.AppendLine("// GetRegistrations() was not generated because this registry already declares it.");
                builder.AppendLine("// Remove the user-defined GetRegistrations() stub to enable source-generated registrations.");
                builder.AppendLine("}");
                return;
            }

            builder.AppendLine("/// <inheritdoc />")
                .AppendLine($"public global::System.Collections.Generic.IEnumerable<global::SuperSocket.Command.CommandRegistration<{registry.KeyTypeFullName}, {registry.PackageInfoTypeFullName}>> GetRegistrations()")
                .AppendLine("{");

            using (builder.Indent())
            {
                var emittedCommandsByKey = new Dictionary<string, CommandModel>(StringComparer.Ordinal);

                foreach (CommandModel command in commands.OrderBy(static command => command.FullTypeName, StringComparer.Ordinal))
                {
                    PackageMatchKind packageMatch = GetPackageMatch(registry, command);

                    if (packageMatch == PackageMatchKind.None)
                    {
                        continue;
                    }

                    string? keyLiteral = GetEffectiveKeyLiteral(registry, command);

                    if (keyLiteral is null)
                    {
                        ReportMissingKeyForNonStringKey(context, command, registry);
                        continue;
                    }

                    if (command.AttributeKeyLiteral is not null && !CanAssignKeyLiteral(registry.KeyTypeFullName, command.AttributeKeyTypeFullName))
                    {
                        ReportInvalidCommandKeyType(context, command, registry);
                        continue;
                    }

                    if (emittedCommandsByKey.TryGetValue(keyLiteral, out CommandModel existingCommand))
                    {
                        ReportDuplicateKey(context, existingCommand, command, keyLiteral);
                        continue;
                    }

                    foreach (string unsupportedFilterTypeName in command.UnsupportedFilterTypeNames)
                    {
                        ReportCommandFilterUnsupported(context, command, unsupportedFilterTypeName);
                    }

                    emittedCommandsByKey.Add(keyLiteral, command);

                    string nameLiteral = FormatStringLiteral(command.AttributeName ?? command.SimpleName);

                    EmitCommandRegistration(builder, registry, command, packageMatch, keyLiteral, nameLiteral);
                }

                builder.AppendLine("yield break;");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
    }

    private static void ReportMissingKeyForNonStringKey(SourceProductionContext context, CommandModel command, RegistryModel registry)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            CommandDiagnostics.MissingKeyForNonStringKey,
            Location.None,
            command.FullTypeName,
            registry.KeyTypeFullName));
    }

    private static void ReportDuplicateKey(SourceProductionContext context, CommandModel existingCommand, CommandModel duplicateCommand, string keyLiteral)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            CommandDiagnostics.DuplicateKey,
            Location.None,
            existingCommand.FullTypeName,
            duplicateCommand.FullTypeName,
            keyLiteral));
    }

    private static void ReportCommandFilterUnsupported(SourceProductionContext context, CommandModel command, string filterTypeName)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            CommandDiagnostics.CommandFiltersIgnored,
            Location.None,
            command.FullTypeName,
            filterTypeName));
    }

    private static void ReportInvalidCommandKeyType(SourceProductionContext context, CommandModel command, RegistryModel registry)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            CommandDiagnostics.InvalidCommandKeyType,
            Location.None,
            command.FullTypeName,
            command.AttributeKeyTypeFullName ?? "unknown",
            registry.KeyTypeFullName));
    }

    private static void ReportExistingGetRegistrations(SourceProductionContext context, RegistryModel registry)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            CommandDiagnostics.ExistingGetRegistrations,
            Location.None,
            string.IsNullOrWhiteSpace(registry.Namespace) ? registry.ClassName : registry.Namespace + "." + registry.ClassName));
    }

    private static bool CanAssignKeyLiteral(string targetTypeFullName, string? sourceTypeFullName)
    {
        if (sourceTypeFullName is null)
        {
            return false;
        }

        string targetType = NormalizeTypeName(targetTypeFullName);
        string sourceType = NormalizeTypeName(sourceTypeFullName);

        return string.Equals(sourceType, targetType, StringComparison.Ordinal)
            || string.Equals(targetType, "object", StringComparison.Ordinal)
            || (string.Equals(sourceType, "null", StringComparison.Ordinal) && !IsNonNullablePrimitive(targetType))
            || IsImplicitNumericConversion(sourceType, targetType);
    }

    private static string NormalizeTypeName(string typeName)
    {
        return typeName switch
        {
            "global::System.String" => "string",
            "global::System.Char" => "char",
            "global::System.Boolean" => "bool",
            "global::System.Byte" => "byte",
            "global::System.SByte" => "sbyte",
            "global::System.Int16" => "short",
            "global::System.UInt16" => "ushort",
            "global::System.Int32" => "int",
            "global::System.UInt32" => "uint",
            "global::System.Int64" => "long",
            "global::System.UInt64" => "ulong",
            "global::System.Single" => "float",
            "global::System.Double" => "double",
            "global::System.Object" => "object",
            _ => typeName,
        };
    }

    private static bool IsNonNullablePrimitive(string typeName)
    {
        return typeName is "char" or "bool" or "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "float" or "double";
    }

    private static bool IsImplicitNumericConversion(string sourceType, string targetType)
    {
        return sourceType switch
        {
            "sbyte" => targetType is "short" or "int" or "long" or "float" or "double",
            "byte" => targetType is "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "float" or "double",
            "short" => targetType is "int" or "long" or "float" or "double",
            "ushort" => targetType is "int" or "uint" or "long" or "ulong" or "float" or "double",
            "int" => targetType is "long" or "float" or "double",
            "uint" => targetType is "long" or "ulong" or "float" or "double",
            "long" => targetType is "float" or "double",
            "ulong" => targetType is "float" or "double",
            "float" => targetType is "double",
            _ => false,
        };
    }

    private static PackageMatchKind GetPackageMatch(RegistryModel registry, CommandModel command)
    {
        if (string.Equals(command.PackageTypeFullName, registry.PackageInfoTypeFullName, StringComparison.Ordinal))
        {
            return PackageMatchKind.Exact;
        }

        if (!command.PackageTypeIsInterface)
        {
            return PackageMatchKind.None;
        }

        return registry.PackageInfoInterfaceTypeFullNames.Contains(command.PackageTypeFullName, StringComparer.Ordinal)
            ? PackageMatchKind.Interface
            : PackageMatchKind.None;
    }

    private static void EmitCommandRegistration(
        SourceBuilder builder,
        RegistryModel registry,
        CommandModel command,
        PackageMatchKind packageMatch,
        string keyLiteral,
        string nameLiteral)
    {
        builder.AppendLine($"yield return new global::SuperSocket.Command.CommandRegistration<{registry.KeyTypeFullName}, {registry.PackageInfoTypeFullName}>(")
            .AppendLine($"    {keyLiteral},")
            .AppendLine($"    typeof({command.FullTypeName}),");

        if (packageMatch == PackageMatchKind.Exact)
        {
            EmitDirectFactory(builder, registry, command, keyLiteral, nameLiteral);
        }
        else
        {
            EmitWrappedFactory(builder, registry, command, keyLiteral, nameLiteral);
        }
    }

    private static void EmitDirectFactory(
        SourceBuilder builder,
        RegistryModel registry,
        CommandModel command,
        string keyLiteral,
        string nameLiteral)
    {
        builder.AppendLine($"    static (sp, options) => new global::SuperSocket.Command.TypedCommandSet<{registry.KeyTypeFullName}, {command.SessionTypeFullName}, {registry.PackageInfoTypeFullName}>(")
            .AppendLine($"        {keyLiteral},")
            .AppendLine($"        new global::SuperSocket.Command.CommandMetadata({nameLiteral}, {keyLiteral}),")
            .AppendLine($"        global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{command.FullTypeName}>(sp),")
            .AppendLine($"        options.CreateCommandFilters(sp, {FormatFiltersExpression(command)})));");
    }

    private static void EmitWrappedFactory(
        SourceBuilder builder,
        RegistryModel registry,
        CommandModel command,
        string keyLiteral,
        string nameLiteral)
    {
        string wrapperTypeName = command.IsAsync
            ? "AsyncCommandWrap"
            : "CommandWrap";

        builder.AppendLine("    static (sp, options) =>")
            .AppendLine("    {")
            .AppendLine($"        {command.FullTypeName} command = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{command.FullTypeName}>(sp);")
            .AppendLine($"        return new global::SuperSocket.Command.TypedCommandSet<{registry.KeyTypeFullName}, {command.SessionTypeFullName}, {registry.PackageInfoTypeFullName}>(")
            .AppendLine($"            {keyLiteral},")
            .AppendLine($"            new global::SuperSocket.Command.CommandMetadata({nameLiteral}, {keyLiteral}),")
            .AppendLine($"            new global::SuperSocket.Command.{wrapperTypeName}<{command.SessionTypeFullName}, {registry.PackageInfoTypeFullName}, {command.PackageTypeFullName}, {command.FullTypeName}>(command),")
            .AppendLine($"            options.CreateCommandFilters(sp, {FormatFiltersExpression(command)}));")
            .AppendLine("    });");
    }

    private static string FormatFiltersExpression(CommandModel command)
    {
        if (command.Filters.Count == 0)
        {
            return "global::System.Array.Empty<global::SuperSocket.Command.ICommandFilter>()";
        }

        var filters = new List<string>(command.Filters.Count);

        foreach (FilterAttributeModel filter in command.Filters)
        {
            filters.Add(FormatFilterInstantiation(filter));
        }

        return "new global::SuperSocket.Command.ICommandFilter[] { " + string.Join(", ", filters) + " }";
    }

    private static string FormatFilterInstantiation(FilterAttributeModel filter)
    {
        string constructorArguments = string.Join(", ", filter.ConstructorArguments.Select(static argument => argument.EmitExpression));
        string constructor = $"new {filter.TypeFullName}({constructorArguments})";

        if (filter.NamedArguments.Count == 0)
        {
            return constructor;
        }

        string namedArguments = string.Join(", ", filter.NamedArguments.Select(static argument => $"{argument.Name} = {argument.Value.EmitExpression}"));

        return constructor + " { " + namedArguments + " }";
    }

    private static string? GetEffectiveKeyLiteral(RegistryModel registry, CommandModel command)
    {
        if (command.AttributeKeyLiteral is not null)
        {
            return command.AttributeKeyLiteral;
        }

        if (!registry.IsKeyString)
        {
            return null;
        }

        return FormatStringLiteral(command.AttributeName ?? command.SimpleName);
    }

    private static string FormatStringLiteral(string value)
    {
        return SymbolDisplay.FormatLiteral(value, true);
    }

    private enum PackageMatchKind
    {
        None,
        Exact,
        Interface,
    }
}
